"""empty message

Revision ID: cb6a234808f8
Revises: 8a2fa7e00b36
Create Date: 2020-06-13 12:41:28.487844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6a234808f8'
down_revision = '8a2fa7e00b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cook_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'cook_time')
    # ### end Alembic commands ###
